### ISSUE TITLE
No sound at all

### ISSUE THREAD

**Issue by pbrinkmeier** [Novare/legendofsajjad#3]
Hi ich schreib jetzt mal auf Deutsch, ist mir jetzt zu lästig.

Mein frisch gebautes LOS spielt keinen Sound. Die Konsole zeigt folgende Meldungen:

    [paul@pupsmuffin8 legendofsajjad.mk]$ ./LegendOfSajjad 
    SRC: soundBank.cpp	ERR: Failed to play sound 3
    SRC: soundBank.cpp	ERR: Failed to play sound 1
    SRC: soundBank.cpp	ERR: Failed to play sound 3
    SRC: soundBank.cpp	ERR: Failed to play sound 3
    SRC: soundBank.cpp	ERR: Failed to play sound 3
    SRC: soundBank.cpp	ERR: Failed to play sound 3

Daten über mein System (Fedora Workstation 25):

    [paul@pupsmuffin8 legendofsajjad.mk]$ uname -a
    Linux pupsmuffin8 4.10.13-200.fc25.x86_64 #1 SMP Thu Apr 27 20:39:25 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by pbrinkmeier** [comment]
Okay, ich bin offiziell 1 bisschen dumm. Hatte den Sound aus und nicht erwartet, dass ein Fehler geworfen wird.

Ich werde einen PR machen, der `Mix_GetError()` zur Ausgabe hinzufügt.

**Comment by Novare** [comment]
Glad the issue got resolved. Please use the English language for consistency's sake and non-German speakers, who might have the same problem, though.
